@startuml
actor User as U
participant OlympicCountryDetailComponent <<Page>>

participant "OlympicService" <<Injectable>>
participant "BoxStatsComponent" as BSC
participant "DetailGraphComponent" as DGC

U -> OlympicCountryDetailComponent: Navigue vers "Olympic Country Detail" (via Router)
activate OlympicCountryDetailComponent
OlympicCountryDetailComponent -> OlympicCountryDetailComponent: Récupère l'ID du pays depuis ActivatedRoute
OlympicCountryDetailComponent -> OlympicService: getOlympicStatsOfCountryId(countryId, showAverages)
activate OlympicService
OlympicService --> OlympicCountryDetailComponent: Renvoie les Stats Olympiques (boxStats$)
deactivate OlympicService

OlympicCountryDetailComponent -> OlympicService: getMedalsDetailGraphOfCountryV2(countryId, showAverages)
activate OlympicService
OlympicService --> OlympicCountryDetailComponent: Renvoie les Données du Graphique (detailChartData$)
deactivate OlympicService

OlympicCountryDetailComponent -> BSC: Alimente le compOlympicServiceant avec boxStats$
OlympicCountryDetailComponent -> DGC: Alimente le compOlympicServiceant avec detailChartData$
deactivate OlympicCountryDetailComponent
@enduml
