@startuml
actor User as U
participant HomeComponent <<Page>>
participant "OlympicService" <<Injectable>>
participant "app-box-stats" as BS
participant "app-global-graph" as GG
participant "Router" <<Injectable>>

U -> HomeComponent: Charge la Page (HomeComponent default path)
activate HomeComponent
HomeComponent -> OlympicService: getHomeStats()
activate OlympicService
OlympicService --> HomeComponent: Renvoie les Stats (boxStats$)
deactivate OlympicService

HomeComponent -> OlympicService: getMedalsGlobalGraph()
activate OlympicService
OlympicService --> HomeComponent: Renvoie les Données Graphiques (globalGraph$)
deactivate OlympicService

HomeComponent -> BS: Fournit les Stats (via Input)
HomeComponent -> GG: Fournit les Données Graphiques (via Input)
deactivate HomeComponent

U -> GG: Sélectionne une tranche/graphique
activate GG
GG -> HomeComponent: Émet un événement (onSelectSlice)
deactivate GG

activate HomeComponent
HomeComponent -> HomeComponent: Analyse l'ID du pays
HomeComponent -> Router: Navigue vers olympic-country-detail
deactivate HomeComponent
@enduml
